import { useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import Icon from '../../components/ui/Icon'
import Button, { IconButton } from '../../components/ui/Button'
import { ConfirmModal } from '../../components/ui/Modal'
import { Callout, DefinitionList } from '../../components/ui/Display'
import { Panel, PropertyStatusBadge } from '../../components/HostUI'
import QRCode from '../../components/QRCode'
import { useWorkspace } from '../../context/WorkspaceContext'
import * as propertyService from '../../services/propertyService'
import { formatDate } from '../../utils/format'

/**
 * Guest access — the handover point between this panel and the guest app.
 *
 * The QR here is a visual placeholder (see components/QRCode.jsx); the copy
 * says so, because a host who prints an unscannable code has a bad week.
 */
export default function GuestAccess() {
  const { property } = useOutletContext()
  const { applyProperty, pushToast } = useWorkspace()
  const [confirm, setConfirm] = useState(null)
  const [busy, setBusy] = useState(false)

  const { link, code, generatedAt, totalGuests, activeGuests } = property.guestAccess
  const live = property.status === 'published' && property.guestAccess.enabled

  const copy = async (value, label) => {
    try {
      await navigator.clipboard.writeText(value)
      pushToast({ tone: 'success', title: `${label} copied`, duration: 2000 })
    } catch {
      pushToast({ tone: 'info', title: 'Copy failed', message: 'Select the text and copy manually.' })
    }
  }

  const share = async () => {
    try {
      if (navigator.share) {
        await navigator.share({ title: property.name, text: 'Your stay details', url: link })
        return
      }
      await copy(link, 'Link')
    } catch {
      /* the host dismissed the share sheet */
    }
  }

  const regenerate = async () => {
    setBusy(true)
    try {
      applyProperty(await propertyService.regenerateGuestAccess(property.id))
      pushToast({
        tone: 'success',
        title: 'New guest link generated',
        message: 'The previous link no longer opens.',
      })
    } catch (error) {
      pushToast({ tone: 'error', title: 'That did not work', message: error.message })
    } finally {
      setBusy(false)
      setConfirm(null)
    }
  }

  const publish = async () => {
    setBusy(true)
    try {
      applyProperty(await propertyService.setPropertyStatus(property.id, 'published'))
      pushToast({ tone: 'success', title: 'Property published', message: 'Guest access is live.' })
    } catch (error) {
      pushToast({ tone: 'error', title: 'That did not work', message: error.message })
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="hgrid hgrid--main-aside">
      <div className="hstack" style={{ gap: 'var(--sp-4)' }}>
        {!live && (
          <Callout icon="alert">
            <strong style={{ display: 'block', marginBottom: 2 }}>Guest access is not live</strong>
            {property.status === 'draft'
              ? 'This property is still a draft. Publish it and the link below starts working.'
              : 'Guest access is paused. Publish the property again to switch it back on.'}
            <div style={{ marginTop: 'var(--sp-3)' }}>
              <Button size="sm" onClick={publish} loading={busy} icon="check">
                Publish property
              </Button>
            </div>
          </Callout>
        )}

        <Panel title="Guest access" subtitle="Share this with anyone staying at the property.">
          <div className="qr-card">
            <div>
              <div className="qr">
                <QRCode value={link} size={176} title={`Guest access for ${property.name}`} />
              </div>
              <p className="u-xs u-muted" style={{ textAlign: 'center', marginTop: 8, maxWidth: 220 }}>
                Placeholder pattern. A scannable code is generated by the backend when access is
                issued.
              </p>
            </div>

            <div className="hstack" style={{ gap: 'var(--sp-3)' }}>
              <div>
                <span className="field__label">Guest link</span>
                <div className="linkbox" style={{ marginTop: 6 }}>
                  <span className="linkbox__value">{link}</span>
                  <IconButton icon="copy" label="Copy guest link" onClick={() => copy(link, 'Link')} />
                </div>
              </div>

              <div>
                <span className="field__label">Access code</span>
                <div className="linkbox" style={{ marginTop: 6 }}>
                  <span className="linkbox__value" style={{ letterSpacing: '0.1em' }}>
                    {code}
                  </span>
                  <IconButton icon="copy" label="Copy access code" onClick={() => copy(code, 'Code')} />
                </div>
              </div>

              <div className="hrow">
                <Button icon="share" onClick={share}>
                  Share link
                </Button>
                <Button
                  variant="secondary"
                  icon="download"
                  onClick={() =>
                    pushToast({
                      tone: 'info',
                      title: 'Download is mocked',
                      message: 'The backend will render a print-ready PNG when access is issued.',
                    })
                  }
                >
                  Download QR
                </Button>
                <Button variant="ghost" icon="play" to={`/host/properties/${property.id}/preview`}>
                  View guest experience
                </Button>
              </div>
            </div>
          </div>
        </Panel>

        <Panel title="What your guests unlock">
          <div className="hgrid hgrid--2">
            <div>
              <p className="field__label" style={{ marginBottom: 8 }}>
                <Icon name="lock" size={14} style={{ verticalAlign: '-2px', marginRight: 6 }} />
                Private to your guests
              </p>
              <ul className="hstack" style={{ gap: 6 }}>
                {[
                  'WiFi network and password',
                  'Check-in time, door and gate codes',
                  'Check-out steps',
                  'House rules',
                  'Parking instructions',
                  'Emergency contacts',
                  'Your local recommendations',
                ].map((item) => (
                  <li key={item} className="u-row" style={{ alignItems: 'flex-start', gap: 8 }}>
                    <Icon name="check" size={15} style={{ color: 'var(--sea-500)', flex: 'none', marginTop: 3 }} />
                    <span className="u-small u-muted">{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <p className="field__label" style={{ marginBottom: 8 }}>
                <Icon name="globe" size={14} style={{ verticalAlign: '-2px', marginRight: 6 }} />
                Public to everyone
              </p>
              <ul className="hstack" style={{ gap: 6 }}>
                {[
                  'Beaches and beach guides',
                  'Restaurants across 30A',
                  'Bonfires, bikes, boats, golf carts',
                  'Events and local partners',
                  'The map and general 30A information',
                ].map((item) => (
                  <li key={item} className="u-row" style={{ alignItems: 'flex-start', gap: 8 }}>
                    <Icon name="check" size={15} style={{ color: 'var(--ink-300)', flex: 'none', marginTop: 3 }} />
                    <span className="u-small u-muted">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Panel>

        <Panel title="How to share it">
          <ol className="steps-list">
            <li>Paste the link into your booking confirmation or check-in message.</li>
            <li>Print the QR code on the welcome card, or stick it inside the front door.</li>
            <li>
              Guests open it once. From then on their phone remembers the stay for the length of the
              booking.
            </li>
          </ol>
        </Panel>
      </div>

      <div className="hstack" style={{ gap: 'var(--sp-4)' }}>
        <Panel title="Status">
          <div className="u-between">
            <span className="u-small u-muted">Guest access</span>
            <PropertyStatusBadge status={property.status} />
          </div>
          <DefinitionList
            className="hsection"
            rows={[
              { key: 'Guests so far', value: totalGuests },
              { key: 'In the house now', value: activeGuests },
              {
                key: 'Link generated',
                value: generatedAt
                  ? formatDate(generatedAt, { month: 'short', day: 'numeric', year: 'numeric' })
                  : 'Not yet',
              },
            ]}
          />
        </Panel>

        <Panel title="Security">
          <p className="u-small u-muted" style={{ lineHeight: 1.65 }}>
            Anyone holding this link can see your private property information. Regenerate it if a
            link has been shared beyond the guests you meant it for.
          </p>
          <Button
            variant="secondary"
            block
            icon="refresh"
            style={{ marginTop: 'var(--sp-3)' }}
            onClick={() => setConfirm('regenerate')}
          >
            Regenerate link
          </Button>
        </Panel>
      </div>

      <ConfirmModal
        open={confirm === 'regenerate'}
        onClose={() => setConfirm(null)}
        onConfirm={regenerate}
        loading={busy}
        title="Regenerate the guest link?"
        message="The current link and QR code stop working immediately, including for guests currently staying. You will need to send the new link to anyone already booked."
        confirmLabel="Regenerate link"
        tone="danger"
      />
    </div>
  )
}
